trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: BuildAndDeploy
  jobs:
  - job: BuildDockerImage
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'meityeli-ExcuseME-616e1a07-2d0d-4672-8ebf-93de336eb98b'
        repository: 'excuseme-rg/excuseme-wa'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(Build.BuildId)

  - job: DeployToAKS
    steps:
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '3.x'
        installationPath: $(Agent.ToolsDirectory)/dotnet
    - task: KubernetesManifest@0
      inputs:
        action: 'deploy'
        kubernetesServiceConnection: 'my-aks-cluster-connection'
        namespace: 'default'
        manifests: 'manifest/*.yml'

