apiVersion: apps/v1
kind: Deployment
metadata:
  name: excuseme-wa-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: excuseme-wa
  template:
    metadata:
      labels:
        app: excuseme-wa
    spec:
      containers:
      - name: excuseme-wa
        image: excusemeacr.azurecr.io:v1.0
        ports:
        - containerPort: 80

